# Generated by Django 4.1.2 on 2023-11-01 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 7, 28), verbose_name='closing date * '),
        ),
        migrations.AlterField(
            model_name='votingpoll',
            name='preference_model',
            field=models.CharField(choices=[('Approval', 'Approval Voting (Yes / No)'), ('Ranks#0', 'Simpson voting'), ('Ranks#2', 'Borda voting'), ('Ranks#1', 'Copeland voting'), ('Ranks#3', 'Hare voting'), ('Ranks#4', 'Schulze voting')], default='PositiveNegative', max_length=50, verbose_name='Preference model * '),
        ),
    ]
