# Generated by Django 4.1.2 on 2023-11-23 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_csvupload_alter_poll_closing_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUpload',
        ),
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 8, 19), verbose_name='closing date * '),
        ),
    ]
