# Generated by Django 4.1.2 on 2023-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=255)),
                ('column2', models.IntegerField()),
            ],
        ),
    ]
