# Generated by Django 4.1.2 on 2023-11-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_polldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polldata',
            name='column2',
        ),
    ]
