# Generated by Django 4.1.2 on 2023-11-27 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_voter_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 8, 23), verbose_name='closing date * '),
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
