# Generated by Django 4.1.2 on 2023-12-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_poll_closing_date_mypollappuseranonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycandidatepreference',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.candidate'),
        ),
    ]
