# Generated by Django 4.1.2 on 2023-12-27 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_mycandidatepreference_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 9, 22), verbose_name='closing date * '),
        ),
    ]
