# Generated by Django 4.1.2 on 2024-01-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_poll_closing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingpoll',
            name='method',
            field=models.CharField(default='50', max_length=50, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='votingpoll',
            name='preference_model',
            field=models.CharField(choices=[('Approval', 'Approval Voting (Yes / No)'), ('Ranks#0', 'Simpson voting'), ('Ranks#2', 'Borda voting'), ('Ranks#4', 'Copeland voting'), ('Ranks#6', 'schulze voting'), ('Ranks#8', 'Hare voting')], default='PositiveNegative', max_length=50, verbose_name='Preference model * '),
        ),
    ]
