# Generated by Django 4.1.2 on 2024-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_votingpoll_method_alter_votingpoll_preference_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingpoll',
            name='method',
            field=models.CharField(max_length=50, verbose_name='Method'),
        ),
    ]
