# Generated by Django 4.1.2 on 2024-01-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_votingpoll_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingpoll',
            name='preference_model',
            field=models.CharField(choices=[('Approval', 'Approval Voting (Yes / No)'), ('Ranks#0', 'Simpson voting'), ('Ranks#2', 'Borda voting'), ('Ranks#4', 'Copeland voting'), ('Ranks#6', 'Schulze voting'), ('Ranks#8', 'Hare voting')], default='PositiveNegative', max_length=50, verbose_name='Preference model * '),
        ),
    ]
