# Generated by Django 4.1.2 on 2024-02-08 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_votingpoll_preference_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 11, 4), verbose_name='closing date * '),
        ),
    ]
