# Generated by Django 4.1.2 on 2024-02-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useranonymous_poll'),
        ('polls', '0023_alter_poll_closing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='rank')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.candidate', verbose_name='candidate')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.votingpoll', verbose_name='poll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='voter')),
            ],
            options={
                'ordering': ['voter', 'poll', 'rank'],
                'unique_together': {('voter', 'poll', 'candidate')},
            },
        ),
    ]
