# Generated by Django 4.1.2 on 2024-02-09 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_votingpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 11, 5), verbose_name='closing date * '),
        ),
    ]
