# Generated by Django 4.1.2 on 2024-02-11 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_poll_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(default=datetime.date(2026, 11, 7), verbose_name='closing date * '),
        ),
    ]
