# Generated by Django 4.1.2 on 2024-02-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_poll_closing_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VotingPreference',
        ),
    ]
